name: CLIP
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - cuda-cccl=12.8.55
  - cuda-cccl_win-64=12.8.55
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.8.55
  - cuda-opencl-dev=12.8.55
  - cuda-profiler-api=12.8.55
  - cuda-runtime=12.1.0
  - cuda-version=12.8
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.5
  - jpeg=9e
  - khronos-opencl-icd-loader=2024.05.08
  - lcms2=2.16
  - lerc=4.0.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.9.55
  - libcurand-dev=10.3.9.55
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.4.2
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pillow=11.1.0
  - pip=25.0
  - pysocks=1.7.1
  - python=3.10.16
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools=75.8.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - altair==5.5.0
      - attrs==25.1.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - click==8.1.8
      - clip==1.0
      - colorama==0.4.6
      - fsspec==2025.2.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - narwhals==1.27.1
      - packaging==24.2
      - pandas==2.2.3
      - protobuf==5.29.3
      - pyarrow==19.0.1
      - pydeck==0.9.1
      - pygments==2.19.1
      - pyqt6==6.8.1
      - pyqt6-qt6==6.8.2
      - pyqt6-sip==13.10.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - referencing==0.36.2
      - regex==2024.11.6
      - rich==13.9.4
      - rpds-py==0.23.0
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.42.2
      - tenacity==9.0.0
      - toml==0.10.2
      - torchaudio==2.4.0
      - torchvision==0.19.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - tzdata==2025.1
      - watchdog==6.0.0
      - wcwidth==0.2.13
